package com.connect.backend.domian.customerprofile;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import static com.connect.backend.service.OfyService.ofy;

import com.connect.backend.authenticators.FireAuth;
import com.connect.backend.domian.seprofile.Profile;
import com.connect.backend.domian.utilities.WrappedBoolean;
import com.connect.backend.domian.utilities.queries.GeneralQueryUtils;
import com.connect.backend.forms.ServiceReqForms;
import com.google.api.server.spi.config.AnnotationBoolean;
import com.google.api.server.spi.config.ApiResourceProperty;
import com.google.appengine.repackaged.com.google.api.client.util.Preconditions;
import com.googlecode.objectify.Key;
import com.googlecode.objectify.Work;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;
import com.googlecode.objectify.annotation.Parent;
@Entity
public class ServiceReq{
	public static final Logger logger=Logger.getLogger(FireAuth.class.getName());

	
	@Id
	private long id;
	
	@Parent
	@ApiResourceProperty(ignored = AnnotationBoolean.TRUE)
	private Key<Client> parentKey;
	
	@ApiResourceProperty(ignored = AnnotationBoolean.TRUE)
	private List<Key<Profile>> servicePeopleKeys;  //list of service people to get access to the request
	
	private List<String> webSafeServicePeopleKeys;  //string keys version
	
	private String serviceDescription;        //description of service needed, to be provided by customer 
	
	private String dateOfRequest;                  //automatically generated by constructor
	
	private  String serviceStartDay;    //to be provided by customer
	
	private String resposeDeadlineTime;     //to be calculated by constructor
	
	private String webSafeServiceReqKey;
	
	private int unavailableProfiles=0;
	
	public ServiceReq(){};
	
	
	public ServiceReq(long id, long clientId, ServiceReqForms serviceReqForms,List<String> webSafeServicePeopleKeys){
		
		
		
		Preconditions.checkNotNull(serviceReqForms.getServiceStartDay(), "Start date can't be null");
		Preconditions.checkNotNull(serviceReqForms.getServiceDescription(), "Description of service wanted can't be null");
		Preconditions.checkNotNull(webSafeServicePeopleKeys, "SE personel profile keys must be sent too");
	
		
        this.id=id;
		
		this.parentKey=Key.create(Client.class, clientId);
		
		this.webSafeServicePeopleKeys=webSafeServicePeopleKeys;
		
		
		
		this.servicePeopleKeys= new ArrayList<>();
		
		for(String iterate: webSafeServicePeopleKeys)
		{
			Key<Profile> proflie=Key.create(iterate);
			this.servicePeopleKeys.add(proflie);
			
			
		}
		
		this.serviceStartDay=GeneralQueryUtils.TimeUtils.checkDateStrings(serviceReqForms.getServiceStartDay());
		
		this.serviceDescription=serviceReqForms.getServiceDescription();
		
		this.webSafeServiceReqKey=Key.create(ServiceReq.class, id).getString();
		
		Date date=new Date();
		this.dateOfRequest=GeneralQueryUtils.TimeUtils.simpleDateFormat.format(date);
		
		this.resposeDeadlineTime=calcResponseDeadline();
		
		sendRequests();
					
			
	}
	
	private String calcResponseDeadline()
	{
		int interval=GeneralQueryUtils.TimeUtils.dateInterval(this.dateOfRequest, this.serviceStartDay); // calculate the time interval between dateOfrequest and serviceStartDay
		
		double inter=(double) interval;           ///convert to double so we can calculate percentages
		
		inter=inter*0.2;                           //get 20%  of the double value
		
		String dateEstimate=GeneralQueryUtils.TimeUtils.dateFowardEst(this.dateOfRequest,(int)inter);
		
		return dateEstimate;
	}
	
	
	public WrappedBoolean sendRequests()
	{
		WrappedBoolean requestStatus=ofy().transact(new Work<WrappedBoolean>() {
			
			@Override
			public WrappedBoolean run(){
				
				Collection<Profile> loadedProfileKeys=ofy().load().keys(servicePeopleKeys).values();
				if(loadedProfileKeys==null) return new WrappedBoolean(false,"There are no SE profiles to send to");
				 
				
				List<Profile> profiles= new ArrayList<>(loadedProfileKeys);
				
				 Key<ServiceReq> requestKey=Key.create(ServiceReq.class,id);
				 
				
				for(Profile iterate:profiles)

				{  	
					boolean status=false;

					
				   if(iterate!=null) status=iterate.addServiceRequest(requestKey);
				   if(iterate==null||status==false)	unavailableProfiles++;
					
				}
				
				    ofy().save().entities(profiles);
					
					
			     
				
				return new WrappedBoolean(true);
				
				
			}
			
			
			
		});
		
		
		return requestStatus;
	}
	
	


	public String getServiceDescription(){return serviceDescription;}
	public String getDateOfRequest(){return dateOfRequest;}
	public String getServiceStarDay(){return serviceStartDay;}
	public String getResponseDeadlineTime(){return resposeDeadlineTime;}
	public List<String>getWebSafeServicePeopleKeys(){return webSafeServicePeopleKeys;}
	public String getWebSafeServiceReqKey(){return webSafeServiceReqKey;}
	public int getUnavailableProfiles(){return unavailableProfiles;}
}